### ISSUE TITLE
Missing template processor

### ISSUE THREAD

**Issue by buschtoens** [tildeio/ts-std#8]
I wanted to add this package as a dev dependency to an internal addon of mine. The addon is using module unification, in case that matters. Anyhow, running `ember s` in the addon triggers this error:

```js
Error: Missing template processor
    at module.exports.preprocessTemplates (/Users/janbuschtoens/clark/application/node_modules/ember-cli-preprocess-registry/preprocessors.js:158:11)
    at Class.treeForSrc (/Users/janbuschtoens/clark/application/client-packages/addons/forms/node_modules/ember-cli/lib/models/addon.js:804:39)
    at Class._treeFor (/Users/janbuschtoens/clark/application/client-packages/addons/forms/node_modules/ember-cli/lib/models/addon.js:616:33)
    at Class.treeFor (/Users/janbuschtoens/clark/application/client-packages/addons/forms/node_modules/ember-cli/lib/models/addon.js:576:21)
    at project.addons.reduce (/Users/janbuschtoens/clark/application/client-packages/addons/forms/node_modules/ember-cli/lib/broccoli/ember-app.js:700:26)
    at Array.reduce (<anonymous>)
    at EmberAddon._addonTreesFor (/Users/janbuschtoens/clark/application/client-packages/addons/forms/node_modules/ember-cli/lib/broccoli/ember-app.js:698:32)
    at EmberAddon._addonBundles (/Users/janbuschtoens/clark/application/client-packages/addons/forms/node_modules/ember-cli/lib/broccoli/ember-app.js:1161:31)
    at EmberAddon.createAddonTree (/Users/janbuschtoens/clark/application/client-packages/addons/forms/node_modules/ember-cli/lib/broccoli/ember-app.js:1194:29)
    at EmberAddon.addonSrcTree (/Users/janbuschtoens/clark/application/client-packages/addons/forms/node_modules/ember-cli/lib/broccoli/ember-app.js:1225:39)
```

Is there a reason that this addon has an `ember-addon` configuration? Seeing that this is supposed to be a TS std lib, shouldn't these framework specifics be extracted out of the core library?

**Comment by buschtoens** [comment]
FWIW adding [`shouldIncludeChildAddon`](https://ember-cli.com/api/classes/Addon.html#method_shouldIncludeChildAddon) to the `index.js` excludes `ts-std` from processing:

```js
  shouldIncludeChildAddon(childAddon) {
    // @see https://github.com/tildeio/ts-std/issues/8
    if (childAddon.name === 'ts-std') {
      return false;
    }
    return this._super.shouldIncludeChildAddon.call(this, childAddon);
  }
```
